In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("cleaned_data_combined_modified.csv")

In [9]:

from cleanDataQ3Q6 import *

carbonated drink
gingerale
the avengers
no drink
jarritos
carbonated drinks
fish sauce
no drink
no drink
none
korea drinkjapanese drink
any drink works well
sprindrift
gingerale
any drink would pair well
laban
gingerale
no drink
laban
yogurt
soft
i have no idea i dont eat that stuff
no drink
dairy
no drink
['coca-cola', 'soda', 'tea', 'lemonade', 'wine', 'sprite', 'water', 'soup', 'fanta', 'mountain dew', 'beer', 'pepsi', 'juice', 'ginger ale', 'dr pepper', 'milk', 'ayran', nan, 'lassi', 'carbonated drink', 'gingerale', 'the avengers', 'no drink', 'jarritos', 'carbonated drinks', 'soju', 'sake', 'calpis', 'fish sauce', 'ocha', 'martini', 'bubble tea', 'none', 'korea drinkjapanese drink', 'champagne', '7up', 'any drink works well', 'canada dry ginger ale', 'gatorade', 'sprindrift', 'cocktail', 'rum', 'smoothie', 'any drink would pair well', 'laban', 'coffee', 'barbican', 'yogurt', 'leban', 'soft', 'i have no idea i dont eat that stuff', 'dairy', 'powerade', 'soy sauce', 'ramune', 'mango pulp', 'diet brisk', 'yakult', 'saporo', 'alcohol', 'baijiu']
  Q6: What drink would you pair with this food item? Q6_cleaned  Label
0                                               Coke  coca-cola  Pizza
1                                               Coke  coca-cola  Pizza
2                                               Cola  coca-cola  Pizza
3                                               Soda       soda  Pizza
4                                               Coke  coca-cola  Pizza

In [10]:
df.head()

,id,"Q1: From a scale 1 to 5, how complex is it to make this food? (Where 1 is the most simple, and 5 is the most complex)",Q2: How many ingredients would you expect this food item to contain?,Q3: In what setting would you expect this food to be served? Please check all that apply,Q4: How much would you expect to pay for one serving of this food item?,Q5: What movie do you think of when thinking of this food item?,Q6: What drink would you pair with this food item?,"Q7: When you think about this food item, who does it remind you of?",Q8: How much hot sauce would you add to this food item?,Label
0,716549,3,6,"Week day lunch,At a party,Late night snack",5,Cloudy with a Chance of Meatballs,coca-cola,Friends,A little (mild),Pizza
1,715742,4,"bread, meet","Week day lunch,At a party,Late night snack",5$ for a large piece,All sort of american young boy movies,coca-cola,"Friends,Teachers,Strangers",NaN,Pizza
2,727333,3,5,"Week day lunch,Week day dinner,Weekend lunch,W...",10dollar,action movie,coca-cola,Friends,A moderate amount (medium),Pizza
3,606874,4,7-Jun,"Week day lunch,Week day dinner,Weekend lunch,W...",$3,Mamma Mia,soda,"Siblings,Friends,Teachers",I will have some of this food item with my hot...,Pizza
4,505318,2,3 or more,"Week day lunch,Week day dinner,Weekend lunch,W...",$5,Cloudy with a chance of meatballs,soda,"Siblings,Friends",A little (mild),Pizza

In [14]:
q6_col = "Q6: What drink would you pair with this food item?"

df["Q6_cleaned"] = df_test['Q6: What drink would you pair with this food item?'].apply(map_drink)
df[[q6_col, "Q6_cleaned", "Label"]].head()

  Q6: What drink would you pair with this food item? Q6_cleaned  Label
0                                          coca-cola  coca-cola  Pizza
1                                          coca-cola  coca-cola  Pizza
2                                          coca-cola  coca-cola  Pizza
3                                               soda       soda  Pizza
4                                               soda  coca-cola  Pizza